<<<<<<<< Updated upstream:server/migrations/versions/0cbae934e914_create_user_table.py
"""create user table

Revision ID: 0cbae934e914
Revises: 
Create Date: 2025-03-23 14:24:35.267341
========
"""recordモデル

Revision ID: 70f7fdf758ef
Revises: 
Create Date: 2025-03-23 19:33:07.762023
>>>>>>>> Stashed changes:server/migrations/versions/70f7fdf758ef_recordモデル.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< Updated upstream:server/migrations/versions/0cbae934e914_create_user_table.py
revision = '0cbae934e914'
========
revision = '70f7fdf758ef'
>>>>>>>> Stashed changes:server/migrations/versions/70f7fdf758ef_recordモデル.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('received_favor_count', sa.Integer(), nullable=False),
    sa.Column('repaid_favor_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('received_favor_text', sa.String(length=255), nullable=True),
    sa.Column('received_favor_date', sa.DateTime(), nullable=True),
    sa.Column('giver_name', sa.String(length=255), nullable=True),
    sa.Column('repaid_favor_text', sa.String(length=255), nullable=True),
    sa.Column('repaid_favor_date', sa.DateTime(), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_record_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('user')
    # ### end Alembic commands ###
